wip - test

diff --git a/.github/workflows/pest.yml b/.github/workflows/pest.yml
--- a/.github/workflows/pest.yml
+++ b/.github/workflows/pest.yml
@@ -44,6 +44,15 @@ jobs:
     name: PHP ${{ matrix.php }}
 
     steps:
+      - name: Debug containers 🐳
+      - run: |
+          echo "=== Running containers ==="
+          docker ps -a
+          echo
+          echo "=== Ping MySQL service ==="
+          nc -zv mysql 3306 || echo "Cannot reach mysql:3306"
+
+
       - name: Checkout Code 🔎
         uses: actions/checkout@v4
 
